### ISSUE TITLE
[Feature Request] - Lapis lamp

### ISSUE THREAD

**Issue by set92** [OneLemonyBoi/MiniUtilities#101]
**Describe the solution you'd like**
I want to see inside the mob farm, but is totally dark, and if I put some light, the curse earth will disappear. In previous versions of Minecraft I could use a Lapis lamp from Random things https://ftb.fandom.com/wiki/Lapis_Lamp. But I don't know of any option in >1.16, and it could be something nice to have.

**Comment by MorningSage** [comment]
Added in [PR](https://github.com/OneLemonyBoi/MiniUtilities/pull/105).

![image](https://user-images.githubusercontent.com/51978143/141736814-0c04f7e6-33fa-4c10-beaf-5da684ff3b2a.png)

**Comment by iammael** [comment]
I went ahead and compile the latest commit (with @MorningSage PR) and tested the Lapis Lamp.

It doesn't seem to work if Optifine is installed. I don't know if this is something you want to fix or not, but I thought you wanted to know.
