### ISSUE TITLE
[Feature Request] - Information on Drum content when hovering

### ISSUE THREAD

**Issue by iammael** [OneLemonyBoi/MiniUtilities#103]
**Is your feature request related to a problem? Please describe.**
Not an issue.

**Describe the solution you'd like**
Add some information when overing over the item to see the content of a Drum.
Eventually a damage bar indicating the content amount but that's not an mandatory thing.

**Describe alternatives you've considered**
None.

**Additional context**
Example from another mod's thank.

![2021-11-08_21 39 53](https://user-images.githubusercontent.com/7931135/140814982-8736250a-9459-4b64-a959-6e78bc9ca454.png)

**Comment by MorningSage** [comment]
Added in https://github.com/OneLemonyBoi/MiniUtilities/pull/105.

![image](https://user-images.githubusercontent.com/51978143/141737025-b769ced7-d143-4bdd-acce-f22ea09f7d21.png)
![image](https://user-images.githubusercontent.com/51978143/141737064-8d984cbe-13c4-4498-82e3-faf70e9ac4ab.png)

**Comment by iammael** [comment]
Nice PR, some great changes! Thank you
