### ISSUE TITLE
[Feature Request] / [Help] - Way to remove/disable enchantments from this mod

### ISSUE THREAD

**Issue by Elfinlocks** [OneLemonyBoi/MiniUtilities#104]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The Experience Harvester enchantment is insanely OP and I want a way to remove it

**Describe alternatives you've considered**
Perhaps this can be done via datapack, but I don't know how. If you can advise how to do that, that works for me as well. 

**Additional context**
N/A

**Comment by Freebi85** [comment]
I second this for the other enchantments too^^ Seems a bit overkill, and when they appear in the vnailla enchanting table there no way to remove them afaik.

**Comment by foxwhite25** [comment]
install apotheosis and disable it in config
