### ISSUE TITLE
[Bug Report] -

### ISSUE THREAD

**Issue by Solousia** [OneLemonyBoi/MiniUtilities#106]
**Describe the bug**
Kikoku sword can't be enchant with industrial foregoing enchanter and cannot apply enchant to the sword.

**To Reproduce**
1. Make industrial foregoing enchanter, input the xp
2. Put the kikoku sword, but it doesn't enchant.

**Expected behavior**
Expected it to work with the machine

**Screenshots**
Non

**Mod Info (please complete the following information):**
 - Modpack: FTB Oceanblock 1.7.0

**Additional context**

**Comment by OneLemonyBoi** [comment]
Intended for now
