### ISSUE TITLE
Prevent Cursed Earth from spawning mobs when light level is higher than 7

### ISSUE THREAD

**Issue by EDufour96** [OneLemonyBoi/MiniUtilities#108]
**Is your feature request related to a problem? Please describe.**
In EU2, Cursed Earth would only work when light level would normally allow mobs to spawn. This helped to prevent lag on servers and reduce the average entity count. The Cursed Earth from Mini Utilities seem to be spawning mobs no matter the light level, which makes managing and maintaining the mob farm a pain in the butt as well as increases the load on the servers.

**Describe the solution you'd like**
Cursed Earth should be inactive while light level is over 7, allowing for control via carefully laid out redstone lamps or other togglable light sources.

**Describe alternatives you've considered**
Another way could be through direct redstone but wouldnt help with natural spawns if the light level is low.

**Additional context**
This suggestion is irrelevant as of now since Cursed Earth currently reverts to dirt after spawning a single mob, as reported in my previous issue #107 .

**Comment by MorningSage** [comment]
I've already opened a similar issue and preceded to create a pull request to address it.

https://github.com/OneLemonyBoi/MiniUtilities/issues/95
https://github.com/OneLemonyBoi/MiniUtilities/pull/105

**Comment by JustJinxed** [comment]
I can see both behaviors being something users could enjoy. Maybe place a config option for the behavior, and default to cursed earth not reverting into dirt, but turning off when the light level is above 7? The devolving earth could have a config setting just in case someone likes the idea of using cursed earth as an underdark sort of threat?

**Comment by JustJinxed** [comment]
> I've already opened a similar issue and preceded to create a pull request to address it.
> 
> #95 #105

Your content doesn't seem to include anything to turning off spawning given a particular light level? It does seem to stop the cursed earth from turning into dirt though. (I did a pull and build for testing out of curiousity)

**Comment by MorningSage** [comment]
Did I really forget to push that commit... >.<

Ok, never mind, once I get back from my vacation, I'll add that.

Sorry about that.
