### ISSUE TITLE
[Feature Request] - Spawn Mobs from every dimenestion with Blursed Earth 

### ISSUE THREAD

**Issue by keckrich** [OneLemonyBoi/MiniUtilities#114]
**Is your feature request related to a problem? Please describe.**
Right now to get correct behavior in mod packs I have to use the In Control mod. If I could just set a setting to make Blursed Earth spawn mobs from every dimension regardless of what dimension you place it would help. This also would help with mob farms in the void. 

**Describe the solution you'd like**
In the config file, a boolean to spawn all mobs regardless of dimension

**Comment by OneLemonyBoi** [comment]
V-Low Priority
