### ISSUE TITLE
[Bug Report] - Fix Compatibility issues with FTB Mods

### ISSUE THREAD

**Issue by NarigudoBR** [OneLemonyBoi/MiniUtilities#115]
**Describe the bug**
In OceanBlock modpack when you compile the latest commits fromthis repo, the game doesn't eve crash because it cannot generate a valid Json? or something(i dunno). Only works in the updates previous to changes made in rendering, for example wit changes that Morning Sage and I did

**To Reproduce**
Steps to reproduce the behavior(my behavior) :
1. Build the mod
2. Put it on the mods folder
3. Start the Game
4. Cry because it doesn't work

**Expected behavior**
Game to start properly and load the worls without crashes

**Mod Info (please complete the following information):**
 - Forge: 36.2.20
 - MC Version: 1.16.5
 - Mod Version: 1.2.4(dev on github)

**Additional context**
log: https://pastebin.com/0sAj1sJW

**Comment by OneLemonyBoi** [comment]
Fixed in dev
