### ISSUE TITLE
[Feature Request] - Drum have comparator support

### ISSUE THREAD

**Issue by Pultex** [OneLemonyBoi/MiniUtilities#118]
**Is your feature request related to a problem? Please describe.**
Not really a problem just a lack of redstone detection ability

Have a the fluid drum be read by the comparator so it can give a redstone value from 1-15

I have to use another mod to read out the value right now so it can not work with out other mod supporting to use with redstone logic

I like the mod but it takes a LOT of netherite

**Comment by OneLemonyBoi** [comment]
Fixed in dev
