### ISSUE TITLE
[Feature Request] - Enchantment Descriptions

### ISSUE THREAD

**Issue by ObsidianFlight** [OneLemonyBoi/MiniUtilities#119]
**Is your feature request related to a problem? Please describe.**
I have no idea what the enchantment books do, example: Experience Harvester

**Describe the solution you'd like**
Add enchantment descriptions support

**Describe alternatives you've considered**
Add it to the curseforge page

**Comment by ChiefArug** [comment]
Yes please.
This can be done simply by adding these lang keys to the language file, along with descriptions for the enchantments: ```
enchantment.miniutilities.molten_head.desc
enchantment.miniutilities.experience_harvester.desc
```
