### ISSUE TITLE
[Bug Report] - Ender ore spawn doesn't change

### ISSUE THREAD

**Issue by TGurl** [OneLemonyBoi/MiniUtilities#121]
**Describe the bug**
Changing the spawn settings for Ender Ore doesn't change anything. Ore spawn is still the same as in the original config. Only disabling ore spawn works fine.

**To Reproduce**
[miniutilities-client.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/8008286/miniutilities-client.txt)
[miniutilities-common.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/8008287/miniutilities-common.txt)

1. Change any settings for Ender Ore spawn
2. Generate a new world
3. Check the spawn of Ender Ore with WorldStripper for example.
4. It doesn't matter to what level you set the max-level it keeps at max level 55

**Expected behavior**
Ender Ore spawning should respect the settings in the config tile.

**Screenshots**
None

**Mod Info (please complete the following information):**
 - Forge: 36.2.25
 - MC Version:  1.16.5
 - Mod Version: 1.2.3

**Additional context**
Even setting the max-level to level 2, kept the ores spawning at max-level 55. I used WorldStripper to check the settings.

**Comment by bochen415** [comment]
I came here to report just that, subscribing to get notifications.

**Comment by OneLemonyBoi** [comment]
sadly it does seem that its impossible to access the config from the registry area. technically it is possible to change the feature when the feature is added, but thats not good practice.
