### ISSUE TITLE
[Feature Request] - Utilities Book

### ISSUE THREAD

**Issue by MorganaLaLuna** [OneLemonyBoi/MiniUtilities#122]
**Is your feature request related to a problem? Please describe.**
There's several things that aren't self-explanatory or the uses/requirements are not easily found.
An example would be the use of the enchantments or hot to acquire experience pearls.

**Describe the solution you'd like**
To prevent a lack of information, as the title suggests, add an info book to explain what does what and how to get items relating to the mod.

**Describe alternatives you've considered**
You could also update the description on the Curseforge mod page , though it can be hard to read and most people won't like having to back to the mod page, scroll down, open a spoiler and look for a specific item that may not be there. (*cough* erosion shovel *cough* enchantments *cough*)

**Additional context**
None. Just a request to add some kind of updated source of information for the mod.

**Comment by CapivaraTupiniquim** [comment]
It would be very helpful, I'm really lost with the module!

**Comment by OneLemonyBoi** [comment]
Full In-Game documentation releasing soon, pushed to GH.
