### ISSUE TITLE
[Feature Request] - Next update

### ISSUE THREAD

**Issue by Gogo08190** [OneLemonyBoi/MiniUtilities#125]
What do you think about updating your mod?

**Comment by Shadewing666** [comment]
I'd like to second this please.
Looking through the closed issues, shows that many problems seem to have been fixed since the last uspdate on CurseForge (5 months ago) and it would be great to make the fixes easily available to modpack authors.

**Comment by OneLemonyBoi** [comment]
New version of mod on CF
