### ISSUE TITLE
[Bug Report] - crash trying to break mechanical miner on sp

### ISSUE THREAD

**Issue by epeterse** [OneLemonyBoi/MiniUtilities#129]
[crash-2022-04-14_18.50.33-client.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/8491115/crash-2022-04-14_18.50.33-client.txt)

**Comment by OneLemonyBoi** [comment]
update your lemonlib to 1.4.1

**Comment by epeterse** [comment]
still crashes singleplayer

[crash-2022-04-15_18.51.37-client.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/8497035/crash-2022-04-15_18.51.37-client.txt)
