### ISSUE TITLE
[Bug Report] - Dup laser port with Immersive hammer

### ISSUE THREAD

**Issue by Gogo08190** [OneLemonyBoi/MiniUtilities#131]
**Describe the bug**
Right click with an Engineer's Hammer on a Laser port duplicate it.

**To Reproduce**
1. Place Laser port
2. Right click with a Engineer"s Hammer from Immersive
3. Duplicate Laser port

**Expected behavior**

**Screenshots**

**Mod Info (please complete the following information):**
 - Forge: 36.2.34
 - MC Version: 1.16.5
 - Mod Version: Latest 1.3.1

**Additional context**
https://youtu.be/H9QiAjR-V8k

**Comment by UnicorNora** [comment]
Same for Mechanical Miner with Cresent Hammer
