### ISSUE TITLE
[Bug Report] - Flame Lily Seeds not spawning on 1.18.2

### ISSUE THREAD

**Issue by etherealgears** [OneLemonyBoi/MiniUtilities#133]
**Describe the bug**
Using the 2.0.0 version of this mod for Minecraft 1.18.2, Flame Lily Seeds no longer spawn in desert biomes.

**To Reproduce**
1. Go to a desert biome and fly around in Creative/Spectator.
2. Repeat in multiple different worlds.

**Expected behavior**
Flame Lily Seeds should spawn in desert biomes, like in previous versions of the mod, unless their removal is intentional(?) There's also no crafting recipe for them, unlike Ender Lily Seeds, so since they don't spawn they don't seem attainable in Survival.

**Screenshots**

**Mod Info (please complete the following information):**
 - Forge: 40.1.51
 - MC Version: 1.18.2
 - Mod Version: 2.0.0

**Additional context**

**Comment by OneLemonyBoi** [comment]
Fixed!
