### ISSUE TITLE
[Bug Report] - Mechanical Placer not working correctly.

### ISSUE THREAD

**Issue by ghost** [OneLemonyBoi/MiniUtilities#134]
**Describe the bug**
I tested the Mechanical Placer and it is not working.

**To Reproduce**
1. Place a Menchanical Placer on ground.
2. Open Mechanical Placer with Right-Click.
3. Put blocks inside Menchanical Placer.
4. It does not place any blocks.

**Expected behavior**
Mechanical Placer places block.

**Mod Info (please complete the following information):**
 - Forge: 40.1.60
 - MC Version: 1.18.2
 - Mod Version: 2.0.0

(sorry for my english, i'm not a native speaker)

**Comment by OneLemonyBoi** [comment]
fixed in dev
