### ISSUE TITLE
[Bug Report] - Molten Tool Head not working with Mechanical Miner

### ISSUE THREAD

**Issue by tetuis** [OneLemonyBoi/MiniUtilities#137]
**Describe the bug**
Mined block has not been smelted.

**To Reproduce**
1. Enchant the Iron Pickaxe with a Molten Tool Head.
2. Set the Iron Pickaxe in the Mechanical Miner.
3. Place an Iron Ore block in front of the Mechanical Miner.
4. It contains an Iron Ore.

**Expected behavior**
Iron Ore should be smelted into Iron Ingots.

**Screenshots**
![image](https://user-images.githubusercontent.com/69350996/182628842-c3303827-8b5b-4247-9944-6073a0343fdf.png)

**Mod Info (please complete the following information):**
 - Forge: 36.2.34
 - MC Version: 1.16.5
 - Mod Version: 1.3.2

**Comment by OneLemonyBoi** [comment]
Fixed :)
