### ISSUE TITLE
[Bug Report] - 1.16.5 Villager Lasso

### ISSUE THREAD

**Issue by 77wisher77** [OneLemonyBoi/MiniUtilities#140]
**Describe the bug**
Using the golden lasso on villagers doesn't work, it picks them up but when placing them they return to their original location

**To Reproduce**
1. Go to a villager
2. Click on villager with golden lasso
3. place villager at new location
4. See error - villager has returned to where they came from

**Expected behavior**
Villager should be at the new location

**Screenshots**
none

**Mod Info (please complete the following information):**
 - Forge: forge-36.2.39
 - MC Version: 1.16.5
 - Mod Version: 1.3.2

**Additional context**
Also happens with cows, haven't tested other mobs

**Comment by 77wisher77** [comment]
Update: pigs and chickens seem to work

**Comment by OneLemonyBoi** [comment]
I can't reproduce this at all in testing
