### ISSUE TITLE
[Bug Report] - Multiple controllers are connected to one group of solar panels.

### ISSUE THREAD

**Issue by sashisashi569** [OneLemonyBoi/MiniUtilities#142]
**Describe the bug**
Multiple controllers are connected to a group of solar panels, and energy is produced from each.
**To Reproduce**
Steps(2way)
1.Install panels at least 3x3 in size.
2.Place the controller on the west or south side (make sure that there is no controller within a 3 x 3 area around the controller at this time.)
3.A second controller can be placed at any location in any direction except north. Even in the case of north, it can be placed in almost any location. (The law when the second controller is north is not so well understood.)
4.A controller can be installed to the north only if it is installed to the west and south.
4.1 If the second controller is in the opposite direction of the first, no controller can be placed in the third direction.
Another way
1.If the controller is installed first, it is not affected in any way by the direction in which the controller is installed. (The same applies even if the surrounding blocks are updated.)

**Expected behavior**
As a result, each controller outputs exactly the same amount of energy as the output energy for the same number of panels. 
As an example, assuming 200 panels connected by one controller outputs 200, 200 panels connected by 3 controllers output 600.

**Screenshots**

**Mod Info (please complete the following information):**
 - Forge: 40.1.76
 - MC Version: 1.18.2
 - Mod Version: Miniutilities 2.0.0 Lemonlib 2.1.1

**Additional context**
We recommend trying multiple patterns because the behavior is very puzzling when the panel is already in place.
Although the generation rate appears to have been changed, the behavior was exactly the same before the change.
![2022-12-06_16 26 57](https://user-images.githubusercontent.com/83458880/205852273-e04c1ead-30b8-4bb6-a62d-80896994636e.png)
![2022-12-06_16 27 00](https://user-images.githubusercontent.com/83458880/205852287-4ece2872-788f-4d21-9052-12446067400c.png)

**Comment by OneLemonyBoi** [comment]
Fixed
