### ISSUE TITLE
[Bug Report] - Molten Tool Head destroys many blocks or their data

### ISSUE THREAD

**Issue by IminhaK** [OneLemonyBoi/MiniUtilities#143]
**Describe the bug**
Using molten tool head on some blocks destroys them or drops them but without their data
Tested:
Anvil - destroyed
Tinker's fuel tank - drops as empty
Shulker box - drops as empty
Create's shaft with a belt attached - only drops belt, no shaft

**To Reproduce**
1. Enchant tool with Molten tool head
2. Block drops incorrectly or not at all

**Expected behavior**
Blocks should not be destroyed and their data should be sustained

**Mod Info (please complete the following information):**
 - Forge: 36.2.39
 - MC Version: 1.16.5
 - Mod Version: 1.3.2

**Additional context**
Probably something to do with how the block's drop is determined that's making it incompatible with blocks that carry additional data that affects how it drops (Anvil damage, tinker's fuel contents, shulker contents, create shaft having a belt, etc)

[Line 31 of MoltenHeadHandler.java](https://github.com/OneLemonyBoi/MiniUtilities/blob/1.18.x/src/main/java/onelemonyboi/miniutilities/items/enchantments/MoltenHeadHandler.java#L31) is probably at fault here

**Comment by Sp0okz98** [comment]
This enchantment also bypass any type of spawn protections, factions, worldguard

**Comment by OneLemonyBoi** [comment]
I apologize for the late response, as there has been a lot going on, but a fix will be made soon.

**Comment by OneLemonyBoi** [comment]
Fixed
