### ISSUE TITLE
[Bug Report] - 

### ISSUE THREAD

**Issue by MrEizy** [OneLemonyBoi/MiniUtilities#145]
**Describe the bug**
a regular crash wont work even when i redownload

**To Reproduce**
just add it to 1.19.2 might just be cause of my mods but still

**Expected behavior**
crash

**Mod Info (please complete the following information):**
 - Forge: 43.2.10
 - MC Version: 1.19.2
 - Mod Version: 3.0.0

**Additional context**
[crash-2023-07-12_08.30.18-client.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/12025000/crash-2023-07-12_08.30.18-client.txt)

**Comment by OneLemonyBoi** [comment]
Fixed in new version!
