### ISSUE TITLE
Mini Utilities 1.20.1 - 4.0.0 DEDICATED SERVER CRASH 

### ISSUE THREAD

**Issue by TheWitherlord** [OneLemonyBoi/MiniUtilities#147]
**Describe the bug**
The dedicated server crashes when loaded with the mod version above and FORGE version 1.20.1 - 47.1.0

Could this just be the forge version?

**To Reproduce**
1. download mod
2. run dedicated server
3. crash

**Expected behavior**
Load on a dedicated server

https://gist.github.com/TheWitherlord/0b9c2af368cae9ff734d94dadaec0990

**Comment by Fundryi** [comment]
Any news on this :(?

**Comment by Fundryi** [comment]
Guess this ain't coming any time soon :(?

**Comment by Cguslescop1** [comment]
I have the same problem, you have a solution ?

**Comment by Fundryi** [comment]
Only dev can fix this sadly :(

**Comment by gardenappl** [comment]
Duplicate of #146

**Comment by OneLemonyBoi** [comment]
fixed!
