### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by castilio20** [OneLemonyBoi/MiniUtilities#148]
**Describe the bug**
You can dupe mobs with the gold lasso it should not be stackable
**To Reproduce**
stack 2 lasso catch a mob and unstack the lasso and you get mobs

**Screenshots**

![2023-08-03_11 58 15](https://github.com/OneLemonyBoi/MiniUtilities/assets/76228548/ffd88de0-6920-419f-b306-2846004871d0)
![2023-08-03_11 58 13](https://github.com/OneLemonyBoi/MiniUtilities/assets/76228548/2c827396-cc19-45e7-a07d-694ee62bb151)

**Mod Info (please complete the following information):**
 - Forge: 47.1.3
 - MC Version: 1.201
 - Mod Version: miniutilities-4.0.0

**Comment by 2ndkirbyever** [comment]
This is also happening in 1.19.2.

**Comment by OneLemonyBoi** [comment]
fixed!
