### ISSUE TITLE
[Bug Report - 1.20.1] Can't edit recipes with datapacks, CraftTweaker etc.

### ISSUE THREAD

**Issue by Gbergz** [OneLemonyBoi/MiniUtilities#149]
**Describe the bug**
Recipes can't be removed, nor edited by using datapack loaders or CraftTweaker etc.

**To Reproduce**
1. Attempt to change / remove a recipe
2. reload / restart game
3. recipe is not changed / removed.
4. profit.

**Expected behavior**
That recipes can be removed and edited via crafttweaker and datapacks.

**Screenshots**
None.

**Mod Info (please complete the following information):**
 - Forge: 47.1.3
 - MC Version: 1.20.1
 - Mod Version: 4.0.0 | https://www.curseforge.com/minecraft/mc-mods/miniutilities/files/4638589

**Additional notes**
Would be nice to be able to change recipes and delete recipes if needed.
Mod also crashes on servers, but this is already reported. Hope that gets fixed too.

**Comment by OneLemonyBoi** [comment]
Can't Replicate, not sure why
