### ISSUE TITLE
[Bug Report] - Molten Tool Head Issue

### ISSUE THREAD

**Issue by Baguetteaus** [OneLemonyBoi/MiniUtilities#154]
**Describe the bug**
When a tool that has the Molten Tool Head enchant is used to break a block like sand it becomes unsmeltable in all forms by any mod and furnace. A restart of the server fixes it until someone does it again.

**To Reproduce**
1. Use a tool enchanted with Molten Tool Head to break sand
2. Attempt to smelt sand into glass using a furnace, or another mod that has autosmelt (e.g Ars Noveu, MiningMaster etc.)
3. Unable to Smelt into Glass until Server Restart

**Expected behavior**
The block broken with the Molten Tool head Enchant should smelt the block, and should still allow other methods to smelt the block without requirement of a server restart.

**Screenshots**
![image](https://github.com/OneLemonyBoi/MiniUtilities/assets/142739984/414c540d-4064-4bca-94a5-f00a5827233f)
![image](https://github.com/OneLemonyBoi/MiniUtilities/assets/142739984/d333cdd3-c68b-462a-997e-77be0c70e88c)
![image](https://github.com/OneLemonyBoi/MiniUtilities/assets/142739984/90ae9a62-7bef-42ef-9414-2a989dc5cff4)

**Mod Info (please complete the following information):**
 - Forge: **40.2.9**
 - MC Version: **1.18.2**
 - Mod Version: **2.0.1**

**Additional context**
I am unsure if this affects singleplayer, it could also be a conflict with a mod. I am playing in the Ragnamod 7 Modpack, where we have experienced this issue.

**Comment by OneLemonyBoi** [comment]
1.18.2 is unsupported at the moment, sorry! This is not an issue in newer versions though. Sorry for the inconvenience!
