### ISSUE TITLE
[Bug Report] - Using a golden lasso on another player crashes both of them

### ISSUE THREAD

**Issue by LelouBil** [OneLemonyBoi/MiniUtilities#155]
**Describe the bug**
I am playing this modpack https://www.curseforge.com/minecraft/modpacks/ragnamod-vii which includes MiniUtilities.
I used a golden lasso on another player that had lots of items in his inventory and his backpack.
I got disconnected with "Tried to read NBT tag that was too big", the other player was fine but couldn't place blocks so he disconnected
Now we both can't reconnect and have the same error

**To Reproduce**
1. Get a golden lasso
2. Right-click a player that has lots of items in his inventory and a backpack
3. See the error, now you can't reconnect
4. The other player is bugged, and he won't be able to reconnect if he disconnects

**Expected behavior**
I don't even know what was supposed to happen, but at least do nothing ?

**Screenshots**
![image](https://github.com/OneLemonyBoi/MiniUtilities/assets/13931833/ad0ed3a7-a63e-4bc7-8a3c-742971a625a7)

**Mod Info (please complete the following information):**
 - Forge: 40.2.9
 - MC Version: 1.18.2
 - Mod Version: 2.0.1

**Additional context**

**Comment by Tyranozomby** [comment]
I was the player he used the lasso on.
I didn't crash immediately like him, but a few weird things occurred.
At first, everything seemed fine. I could still take stuff from chests and place blocks. However, after a few, I saw that I couldn't open my backpack anymore, my Curios's slots were all empty (and in an odd order or missing). I couldn't break any block. And after I tried to tp using a waystone, nothing loaded, so logged-out and when I tried to log back in, the error message was here
