### ISSUE TITLE
[Bug Report] - Issue with flight

### ISSUE THREAD

**Issue by ThePansmith** [OneLemonyBoi/MiniUtilities#159]
**Describe the bug**
Issue with flight

**To Reproduce**
1. Attempt to fly, or stop flying
2. Doesn't work

**Expected behavior**
For such an issue to not occur

**Mod Info (please complete the following information):**
 - Forge: latest
 - MC Version: 1.20.1
 - Mod Version: 4.1.0

**Additional context**
Possibly a conflict with another mod, the issue does not persist then Mini Utilities is removed.

**Comment by Deepacat** [comment]
Angel ring flight disables when inventory is updated, and creative flight lets you not double tap space to change state anymore

**Comment by OneLemonyBoi** [comment]
fixed in dev

**Comment by lilrajoo** [comment]
@OneLemonyBoi will u update lemonlib for 1.20.1 forge??

**Comment by EvanHsieh0415** [comment]
confirm in 1.20.1
- mod version: `4.0.0`

**Comment by wkangg** [comment]
still happening in 4.1.0

**Comment by OneLemonyBoi** [comment]
Sorry for the delay, this will be deployed in the next week. Porting to 1.20 is proving to be difficult due to the number of changes made between the versions (including the move to NeoForge).
