### ISSUE TITLE
[Bug Report] - Golden Lasso and Random Patches

### ISSUE THREAD

**Issue by louwenus** [OneLemonyBoi/MiniUtilities#160]
**Describe the bug**
When Random Patches is installed, the golden lasso is bugged:
Whenever a mob (tests made with a cow) is picked up, then placed again, and he try to move, he is teleported back where he was taken

**To Reproduce**
1. Install RandomPatches and Mini Utilities for forge 1.16.5
2. Place a cow in world
3. Grab the cow with a golden lasso, and place her elsewhere 
4. Wait for the cow to move (eventually grab wheat to speed up that)
5. See the cow being TPed back to original position

**Expected behavior**
The golden lasso should work as usual

**Mod Info (please complete the following information):**
 - Forge: 36.2.39
 - MC Version: 1.16.5
 - Mod Version: 1.4.0

**Additional context**
The bug was originally encountered on Forge 36.2.39, but also happen on 36.2.34 (latest stable) and 36.2.42 (latest)

PS;: If you feel this is a RandomPatches bug, feel free to say so, I will transfer this bug report to them

**Comment by OneLemonyBoi** [comment]
I don't think I can fix this on my end, you might want to transfer the bug report to there @louwenus
