### ISSUE TITLE
Ender Ore config

### ISSUE THREAD

**Issue by JadeFalcon** [OneLemonyBoi/MiniUtilities#20]
Changing config values for ender ore is not having any effect, even setting generation to false it still generates.

**Comment by OneLemonyBoi** [comment]
Make sure to check that you have gone far enough and you changed the correct config files. Can you show me your configs?

**Comment by OneLemonyBoi** [comment]
My development environment broke so currently not able to test in dev.

**Comment by JadeFalcon** [comment]
[miniutilities-server.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/6445604/miniutilities-server.txt)

Tried lowering vein size first, then tried fully disabling generation. I did start new worlds both times just to make sure it actually wasn't working.
