### ISSUE TITLE
Mod crashes on load when Curios is not installed

### ISSUE THREAD

**Issue by Random832** [OneLemonyBoi/MiniUtilities#3]
crashes on startup, no other mods installed

version 1.0.0 alpha
forge 1.16.5-36.0.22
[crash-2021-03-23_18.17.04-fml.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/6193070/crash-2021-03-23_18.17.04-fml.txt)

**Comment by Random832** [comment]
The crash seems to be caused by not having Curios installed.

**Comment by OneLemonyBoi** [comment]
Making it a required dependency for the fix.
