### ISSUE TITLE
Using the Experience Pearl doesn't consume the item

### ISSUE THREAD

**Issue by Alexgamer415** [OneLemonyBoi/MiniUtilities#30]
When using the Experience Pearl item, it gives the experience without consuming the item, allowing unlimited experience. 

(Disregard the error, that's from something else)
![image](https://user-images.githubusercontent.com/63180179/118303717-c314d480-b4b3-11eb-9f6f-75e7c8e88ecb.png)

**Comment by OneLemonyBoi** [comment]
fixed
