### ISSUE TITLE
Enchanting kikoku - Levitation effect

### ISSUE THREAD

**Issue by Kimiru** [OneLemonyBoi/MiniUtilities#31]
When enchanting the kikoku on the anvil, i received the levitation effect, but it didn't go away and my character kept going up.
Drinking milk has not removed the effect.

Maybe the duration of the effect is the problem?
Edit: version 1.1.1
![image](https://user-images.githubusercontent.com/34477406/118400826-9d2e3200-b663-11eb-8bfa-97a4d779cd80.png)

**Comment by OneLemonyBoi** [comment]
Fixed in Dev. The levitation effect is a testing effect that i forgot to remove, sorry about the inconvinience
