### ISSUE TITLE
Crash upon Death when killed by mob

### ISSUE THREAD

**Issue by leyxcx** [OneLemonyBoi/MiniUtilities#33]
MC: 1.6.5
Forge: 36.1.16
Mini Utilities Ver: 1.1.1

To Reproduce
1. Load into a world
2. Summon any hostile entity
3. Let it kill you

The cause seems to be the Experience Harvester enchantment if I'm reading the log right

[latest.log](https://github.com/OneLemonyBoi/MiniUtilities/files/6493236/latest.log)

**Comment by TGurl** [comment]
I experience this as well. With nothing just a flat world without armor or anything

1. Load into a flat world
2. Search for a slime
3. Let it kill you

When I remove mini-utilities this crash doesn't happen.

**Comment by OneLemonyBoi** [comment]
Duplicate? of #29. Fixed in dev
