### ISSUE TITLE
Crash with server invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by TGurl** [OneLemonyBoi/MiniUtilities#34]
Minecraft: 1.16.5
Forge: 1.16.5 - 36.1.18
Server: Ubuntu 20.04

When I create server it crashes on startup. I get the following error:

`
Mini Utilities has class loading errors
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER
`
I don't get this error when creating a single-player world

I've tested with java-8 and java-11 on an Ubuntu 20.04 Server with all the latest updates.

[java8-debug.log](https://github.com/OneLemonyBoi/MiniUtilities/files/6494038/java8-debug.log)
[java8-latest.log](https://github.com/OneLemonyBoi/MiniUtilities/files/6494039/java8-latest.log)
[java11-debug.log](https://github.com/OneLemonyBoi/MiniUtilities/files/6494044/java11-debug.log)
[java11-latest.log](https://github.com/OneLemonyBoi/MiniUtilities/files/6494045/java11-latest.log)

**Comment by OneLemonyBoi** [comment]
Dum issue, fixed it! thanks for reporting!
