### ISSUE TITLE
Blursed Earth Light Level

### ISSUE THREAD

**Issue by mellamokb** [OneLemonyBoi/MiniUtilities#35]
I'm using Blursed Earth for a mob farm, but not sure how to disable it?  Seems to ignore light level, I typically use lit redstone lamps to disable the farm.

**Comment by OneLemonyBoi** [comment]
I removed the light level limit as its a mixture of the cursed and blessed, and the blessed has to have light. didn't realize that people need to stop their farms. Will readd light req
