### ISSUE TITLE
Mini Utilities-1.1.1 Crash on Server

### ISSUE THREAD

**Issue by TheWitherlord** [OneLemonyBoi/MiniUtilities#36]
Steps to reproduce:

1. Download the latest version of Mini Utilities
2. Install on dedicated **server**
3. Run server
4. Server crashes

**_Crash report_**
https://gist.github.com/TheWitherlord/8dba05f23b081734955bb290bac77982

**Comment by TGurl** [comment]
Duplicate:
This  was already reported and solved. See under closed  #34
