### ISSUE TITLE
MiniUtilities crashes dedicated server on startup

### ISSUE THREAD

**Issue by Moenish** [OneLemonyBoi/MiniUtilities#37]
I have a modded server running on Forge 36.1.16. I wanted to add MiniUtilities to it, but it keeps crashing the server on startup.
I really want to play with this mod, because it is lightweight enough while having a lot of features for my friends and me.

I tried starting the server with only this mod and it`s dependencies installed, but it crashed anyway.

Here is the log of said crashed startup:
[latest.log](https://github.com/OneLemonyBoi/MiniUtilities/files/6502922/latest.log)

EDIT: Just realized this was mentioned in #34 . But I was running on 1.1.1 (the latest version as far as I know) and it was still crashing.
Can I do something about it now, or it'll only be fixed in an upcoming version?

**Comment by Moenish** [comment]
Just realized this was mentioned in #34. But I was running on 1.1.1 (the latest version as far as I know) and it was still crashing.
Can I do something about it?

**Comment by OneLemonyBoi** [comment]
Will be fixed in upcoming version
