### ISSUE TITLE
Drums and Angel Blocks don't drop themselves when mined

### ISSUE THREAD

**Issue by Random832** [OneLemonyBoi/MiniUtilities#4]
I was surprised by drums not giving me a version with their contents when picked with the middle button in creative mode [that might be a separate enhancement requests], so I switched to survival to mine them to see if they kept their contents, and it didn't drop at all. I checked the loot table JSONs and saw that at least angel blocks have the same problem.

**Comment by OneLemonyBoi** [comment]
Fixed
