### ISSUE TITLE
Mini Utilities 1.1.2 Server Crash  (Still crashes)

### ISSUE THREAD

**Issue by TheWitherlord** [OneLemonyBoi/MiniUtilities#40]
Steps to reproduce:

1. Download the latest version of Mini Utilities
2. Install on a dedicated server
3. Run server
4. Server crashes

https://gist.github.com/TheWitherlord/03f3f0f36e9a287688b703e4978b53ea

**Comment by TheWitherlord** [comment]
Yeah sure thing

**Comment by DracoDej** [comment]
I'm getting the same, basically same crash log.

**Comment by DracoDej** [comment]
I uninstalled mini utilities, and now lemon lib has the same error, though only when attempting to join the server

**Comment by OneLemonyBoi** [comment]
> Different crash, getting somewhere lol
> 
> https://gist.github.com/TheWitherlord/a57f2f4a0730302524ba23f7ef97a6e4

Nice! That means that the issue is solved, ill upload another test file

**Comment by OneLemonyBoi** [comment]
> I uninstalled mini utilities, and now lemon lib has the same error, though only when attempting to join the server

log?

**Comment by DracoDej** [comment]
https://gist.github.com/DracoDej/6b6592b404d8d6e32ccc06800f8c3b83

**Comment by OneLemonyBoi** [comment]
@DracoDej try this: https://github.com/OneLemonyBoi/LemonLib/releases/tag/test

**Comment by TheWitherlord** [comment]
https://gist.github.com/TheWitherlord/830e5c8108ba22d0ab0c7d4026b3ec49

**Comment by DracoDej** [comment]
still crashed.
 https://gist.github.com/DracoDej/73dae71fb6b380bc88edf333d9347f30

**Comment by OneLemonyBoi** [comment]
can both of you use these versions of lemon lib and miniutilities

https://github.com/OneLemonyBoi/LemonLib/releases/tag/test
https://github.com/OneLemonyBoi/MiniUtilities/releases/tag/tests

**Comment by OneLemonyBoi** [comment]
@DracoDej and @TheWitherlord

**Comment by TheWitherlord** [comment]
It works now!

**Comment by OneLemonyBoi** [comment]
YAY!

**Comment by TheWitherlord** [comment]
Is there any way you can release a new curseforge build that has the server fix with it?

**Comment by OneLemonyBoi** [comment]
yup, am releasing now, should be up in a hour

**Comment by TheWitherlord** [comment]
Sounds good!

**Comment by OneLemonyBoi** [comment]
Sorry for the delay, update should be on CF now1
