### ISSUE TITLE
Quarry

### ISSUE THREAD

**Issue by Sunekaer** [OneLemonyBoi/MiniUtilities#42]
1. Quarry still consumes power when its turn off via Redstone.
2. Quarry drops items on the ground if there is no space in inventory, I would recommend stopping the quarry instead. this way you wont crash server by have tons of items on the ground 
3. On your hoverovers for Quarry and other you write RF even tho its called FE now :)

**Comment by OneLemonyBoi** [comment]
Thanks for bringing these issues to my attention! The dropping item was intentional, but now that you bring up that issue, i will change it.

**Comment by OneLemonyBoi** [comment]
Fixed, thanks for your feedback!
