### ISSUE TITLE
Enchanting kikoku duplicates it

### ISSUE THREAD

**Issue by Kimiru** [OneLemonyBoi/MiniUtilities#43]
The kikoku gets duplicated whenever you enchant it with the anvil.
When you close the inventory you get another kikoku, or when you try to put it back into the anvil.

miniutilities-1.1.3
lemonlib-1.3.5

![Screenshot_1](https://user-images.githubusercontent.com/34477406/119451653-d0dd1c00-bd35-11eb-9c9c-2f552ce11011.png)
![Screenshot_2](https://user-images.githubusercontent.com/34477406/119451655-d175b280-bd35-11eb-978a-fcba8c95cb60.png)
![Screenshot_3](https://user-images.githubusercontent.com/34477406/119451647-cfabef00-bd35-11eb-9fde-02d1a802c1ed.png)
![Screenshot_4](https://user-images.githubusercontent.com/34477406/119451651-d0dd1c00-bd35-11eb-8db9-7c24cc5e2432.png)

**Comment by OneLemonyBoi** [comment]
Can you record a video?

**Comment by Kimiru** [comment]
Here is a link to the video.
I should add that I was playing on a server for the this test.
I tried in solo and it did not duplicate

https://drive.google.com/file/d/1OiBRTVuUd0N99IjC1RpWl2xbebECpGfM/view?usp=sharing
