### ISSUE TITLE
Too much info when looking at Drums

### ISSUE THREAD

**Issue by NillerMedDild** [OneLemonyBoi/MiniUtilities#47]
A picture is better than a thousand words? 😄 
Happens in E6 in-dev, miniutilities-1.1.3

![billede](https://user-images.githubusercontent.com/21295394/120040291-8ba33d80-c006-11eb-9c9d-8032b8aeca18.png)

**Comment by OneLemonyBoi** [comment]
Fixed in dev, thanks for reporting!
