### ISSUE TITLE
Quantum quarry not accepting power from Silent's Mechanisms(probably other mods too)

### ISSUE THREAD

**Issue by KrAzYGEEK32** [OneLemonyBoi/MiniUtilities#48]
version: 1.1.3
silent's mechanisms:1.0.1+77
forge: 36.1.0

issue:
quantum quarry seems to only work with the solar panel controller, it doesn't take power from a silent mech battery or wire.

**Comment by OneLemonyBoi** [comment]
Hmm, I will take a look at it but in dev, power IO with my mod's lasers are working fine, and they are using forgecaps

**Comment by MrReps** [comment]
Same prob, with fluxnetwork/refinedpipe/Powah/mekanism
Integrated work
didn't try with more

**Comment by OneLemonyBoi** [comment]
i am dumb and used == when i meant !=, fixing bug now. This is a library issue and will be fixed in 1.3.6 of LemonLib
