### ISSUE TITLE
A Few Requests

### ISSUE THREAD

**Issue by lordeyahyahyah** [OneLemonyBoi/MiniUtilities#50]
Really like the mod just Ender ore spawns a bit too common so I don't have much use for ender lillies and the mechanical miner block doesn't take durability on tools.

Also, you also think it would be possible to add support for ores from other mods for the Quantum Quarry? (Thermal, Mekanism, etc.)

**Comment by OneLemonyBoi** [comment]
you can add your own support after the next update, just waiting on some textures. The miner is meant to not take durability. You can tweak the ender ore in the config
