### ISSUE TITLE
Quantum quarry

### ISSUE THREAD

**Issue by Tenchu98** [OneLemonyBoi/MiniUtilities#54]
The quantum quarry has no interface, doesnt accept rf from what I can tell, and is unbreakable in survival.

**Comment by Rachmaninov13** [comment]
In multiplayer or singleplayer? If the former, as in #52 .

**Comment by OneLemonyBoi** [comment]
yup, duplicate of #52

**Comment by Tenchu98** [comment]
No this was on a MP server.

**Comment by Tenchu98** [comment]
> yup, duplicate of #52

Not a duplicate, as this is on a multiplayer server.

**Comment by OneLemonyBoi** [comment]
SMP is survival multiplayer, so it is a duplicate
