### ISSUE TITLE
Quantum Quarry Weights

### ISSUE THREAD

**Issue by Rachmaninov13** [OneLemonyBoi/MiniUtilities#57]
Right now, from what I see in code and game, the quantum quarry simply reads the JSON, makes a list, and pulls a random ore. This means the weights aren't doing anything. I propose, after the "if (validOreList.size() > 0 " check, to iterate through the validOreList and sum the weight, get Random().nextInt(totalWeight), then iterate through the validOreList again, keeping a running sum of how much weight has been passed, until the random int is reached. The code might look like this, though I apologize if I've made a mistake from my lack of knowledge of Java:

if (validOreList.size() > 0) {
    int totalWeight = 0
    oreItr = validOreList.listIterator()
    while(oreItr.hasNext()){
        totalWeight += oreItr.next().weight
    }
    int randomOre = Random().nextInt(totalWeight)
   // This goes back through the iterator, subtracting weights from the random value.
   // Once that difference goes below zero, we've passed the randomly selected ore.
   // So, return the "previous" value, which is, ironically, "next".
    while(oreItr.hasPrevious() && randomOre > 0){
        randomOre -= oreItr.previous().weight
    }
    return new ItemStack(ForgeRegistries.ITEMS.getValue(ResourceLocation.tryCreate(oreItr.next())))
}

**Comment by OneLemonyBoi** [comment]
the code adds the ore x amount of times to the list, where x is the weight

**Comment by QuImUfu** [comment]
@OneLemonyBoi that is not what the code does, tho. 
I tested it, even if I put in one block at weight 1000 and another one at weight 1, they will be generated roughly as often.
