### ISSUE TITLE
Mechanical Miner and Quantum quarry unusable on SMP?

### ISSUE THREAD

**Issue by Th4tM0nk3y** [OneLemonyBoi/MiniUtilities#61]
Referencing issue #52 , the miner and quantum quarry seem to do nothing and are also not break-able on an SMP, even with version 1.1.3 of the mod.

**Comment by OneLemonyBoi** [comment]
hmm, can you check logs?

**Comment by OneLemonyBoi** [comment]
dont forget to post here

**Comment by Th4tM0nk3y** [comment]
Sorry to come back to you so late, I will send the server and client-logs in here today, since I don't have direct access to the server logs.

**Comment by OneLemonyBoi** [comment]
fixed in dev
