### ISSUE TITLE
Fortune and Molten tool head duplication bug

### ISSUE THREAD

**Issue by p-h-c-s** [OneLemonyBoi/MiniUtilities#62]
If you use a pickaxe with molten tool head and Fortune you can duplicate almost any block.
The problem seems to be around here:
https://github.com/OneLemonyBoi/MiniUtilities/blob/5d651f62bed7cd6f2fdb178ac0ecfdb09649b627/src/main/java/onelemonyboi/miniutilities/items/enchantments/MoltenHeadHandler.java#L40

Reproduced on stacia expert at version 1.1.3

**Comment by Jan-aka-q0** [comment]
Can confirm this is still a thing

**Comment by OneLemonyBoi** [comment]
fixed in dev
