### ISSUE TITLE
[Crash] Dedicated server crashes when mob walks on spike

### ISSUE THREAD

**Issue by sharkck** [OneLemonyBoi/MiniUtilities#64]
[crash-2021-08-02_03.22.31-server.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/6915129/crash-2021-08-02_03.22.31-server.txt)

Running Forge 36.2.0 Dedicated server, latest version of Java with Miniutilities 1.1.3.

Created a Netherite spike and the moment a zombie walked over it, the server crashed with the above log.  If you need more from me just ask!

**Comment by Sunekaer** [comment]
Same crash here_
https://paste.sunekaer.com/mikekadima.rb

**Comment by OneLemonyBoi** [comment]
fixed in dev
