### ISSUE TITLE
GUIs do not work on server

### ISSUE THREAD

**Issue by UnRealDinnerbone** [OneLemonyBoi/MiniUtilities#67]
The Quantum Quarry Block does open a gui when on a server

ModVersion: 1.1.3

**Comment by OneLemonyBoi** [comment]
any errors in logs?

**Comment by MichaelHillcox** [comment]
`19:30:38  [Fatal] [ThreadTaskExecutor/]: Error executing task on Server`

**Comment by OneLemonyBoi** [comment]
fixed in dev
