### ISSUE TITLE
Getting a startup error with the mod.

### ISSUE THREAD

**Issue by TheWitherlord** [OneLemonyBoi/MiniUtilities#72]
Hi again! I love breaking things clearly! Sorry man...

Crash/Failure to start:
https://gist.github.com/TheWitherlord/9c4ef0ae58f6bd9b4500661e75ae234c

When the latest version is installed and you are using lemon lib 1.3.6 the game won't startup.

**Comment by OneLemonyBoi** [comment]
Fixed in 1.2.1
