### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Sunekaer** [OneLemonyBoi/MiniUtilities#73]
The new version 1.2.0 crashes on launch 

https://paste.sunekaer.com/unogelorum.sql

**Comment by OneLemonyBoi** [comment]
this is fixed in 1.2.1, released 5 hrs ago 😄

**Comment by Sunekaer** [comment]
Interesting im only seeing 1.2.0 on curse /shrug

**Comment by OneLemonyBoi** [comment]
<img width="907" alt="Screen Shot 2021-08-21 at 4 31 49 PM" src="https://user-images.githubusercontent.com/50998649/130337307-56a5f467-01d7-4e5e-ac3d-2c2203f6767a.png">
hmm thats interesting

**Comment by Sunekaer** [comment]
Yeah not seeing it on the app, guessing curse are having issues again.
