### ISSUE TITLE
Spikes crash

### ISSUE THREAD

**Issue by nin8995** [OneLemonyBoi/MiniUtilities#82]
When you touch spikes on a server, server crashes leaving the report below.
[crash-2021-08-29_11.20.56-server.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/7072404/crash-2021-08-29_11.20.56-server.txt)

**Comment by OneLemonyBoi** [comment]
is this the newest version

**Comment by OneLemonyBoi** [comment]
Please update your mod version, fixed in a later update
