### ISSUE TITLE
Semi-stable Ingot does not get drained of its durability when its not in the first slot of an hotbar[Bug Report] - 

### ISSUE THREAD

**Issue by TheOnlyMann** [OneLemonyBoi/MiniUtilities#91]
**Describe the bug**
Semi-stable Ingot does not get drained of its durability when its not in the first slot of an hotbar.
**To Reproduce**
1. craft the ingot(or get from creative inventory, idk
2. put it in the first slot of hotbar
3. watch it drain
4. put it in any other slot
5. see it not drain
**Expected behavior**
the ingot durability should drain regardless
**Screenshots**

https://user-images.githubusercontent.com/82017462/134832899-d82d5734-e135-4e8f-a5eb-e946beb49e26.mp4

**Mod Info (please complete the following information):**
 - Forge: 36.2.2
 - MC Version: 1.16.5
 - Mod Version: 1.2.2

**Additional context**

**Comment by OneLemonyBoi** [comment]
fixed in dev
