### ISSUE TITLE
Unstable ingot death message missing[Bug Report] - 

### ISSUE THREAD

**Issue by TheOnlyMann** [OneLemonyBoi/MiniUtilities#92]
**Describe the bug**
When dying to unstable ingot, the death message dont have a proper translation
**To Reproduce**
1. get unstable ingot
2. wait till your doom
3. watch the wierd ass message

**Expected behavior**
it should have a proper death message
**Screenshots**

https://user-images.githubusercontent.com/82017462/134833178-1e4e4aa0-91d2-48cf-86c6-2d646461f30e.mp4

**Mod Info (please complete the following information):**
 - Forge: 36.2.2
 - MC Version: 1.16.5
 - Mod Version: 1.2.2

**Additional context**

**Comment by OneLemonyBoi** [comment]
fixed in 1.2.3
