### ISSUE TITLE
Diamond/netherite spikes dont damage mobs when standed on[Bug Report] - 

### ISSUE THREAD

**Issue by TheOnlyMann** [OneLemonyBoi/MiniUtilities#93]
**Describe the bug**
Diamond/netherite spikes dont damage mobs when standed on
**To Reproduce**
1. Place down spikes
2. check if it doesnt damage you

**Expected behavior**
Diamond/netherite spikes would damage mobs when standed on
**Screenshots**

**Mod Info (please complete the following information):**
 - Forge: 36.2.2
 - MC Version: 1.16.5
 - Mod Version: 1.2.2

**Additional context**

**Comment by Sunekaer** [comment]
https://github.com/OneLemonyBoi/MiniUtilities/pull/90

**Comment by OneLemonyBoi** [comment]
fixed in 1.2.3
