### ISSUE TITLE
[Feature Request] - Proactively Preventing Lag Caused By Blessed/Cursed/Blursed Earth Farms

### ISSUE THREAD

**Issue by MorningSage** [OneLemonyBoi/MiniUtilities#95]
**Is your feature request related to a problem? Please describe.**
By design, earth blocks turn back into dirt when the light level is above 6.  This means that light level cannot be used to disable farms and something more has to be designed if players don't want to either eat the cost of rebuilding their farms or wait for the earth to spread whenever they want to turn it on.  The easy way out is to just leave it running, spawning mobs, dropping items, etc.  This can be bad as it generates a lot of entities (living, item, etc).  In summary, there is no easy way to disable mob spawning and keep your earth blocks and farm intact.

**Describe the solution you'd like**
It would be nice if blocks checked for sky visibility in addition to light level being 7 or above.  If both conditions are met, earth could turn back to dirt.  Otherwise, these blocks would not turn to dirt and simply stop spawning mobs.  With this change, players are able to responsibly and easily disable their farms when drops are not needed and/or storage space is an issue and ultimately preventing servers from wanting to disable this part of the mod due to the rough performance it can cause.

**Describe alternatives you've considered**
The only alternatives that I can see:
1) is placing earth blocks under the walls of your farm as they don't appear to turn to dirt when there's a block above them like normal grass blocks.  When you want to turn your farm on, you then have to let the earth propagate to all the dirt.
2) using some method to place something over your farm (like water for instance) to prevent spawning.

**Additional context**
Both alternative solutions above require additional work/time and most players will either not think of a solution, not understand the server impact of entities, or not care enough to want to put forth the effort.  By adding an additional check, players can easily disable farms like they normally would by turning on lights which is much easier and players will be more likely to spend time doing.

**Comment by Merithor** [comment]
I'd like for this to happen, as I love cursed earth farms, but having to remake is more annoying then anything as glowstone lamps kill the Earth features where it shouldnt "activate" with lamp that isnt direct sunlight.
And if anything on the Blessed earth, it should work if light IS on.
(sorry, this is the only gitthread that has the solutions/issue at hand related to the Earth function).

**Comment by MorningSage** [comment]
This issue is now resolved with the merge of my PR.  Thanks, good sir!

**Comment by OneLemonyBoi** [comment]
fixed by morningsage
