### ISSUE TITLE
Crashing In JEI

### ISSUE THREAD

**Issue by GNRhellraiser** [OneLemonyBoi/MiniUtilities#97]
This could be an error with being in a big mod pack like ATM6 but I'm having an issue when once I load up and the go into JEI interface and @MiniUtlities and hover over an item it crashes happened a few times now

**To Reproduce**
1. load up ATM6
2. Open JEI 
3. Go to @MiniUtilities and hover over an item 

Should be able to look at an item to be able to craft it but as soon as I look at it, it crashes the game

![Capture](https://user-images.githubusercontent.com/92704933/137666758-a4c817eb-f0a5-47dc-bf21-933f5ba028ab.PNG)

**Mod Info (please complete the following information):**
 - Forge: 36.2.6
 - MC Version: 1.16.5
 - Mod Version: All The Mods 6-1.8.7

**Comment by OneLemonyBoi** [comment]
Can you send a crash log?

**Comment by OneLemonyBoi** [comment]
no crash log sent
