### ISSUE TITLE
[Bug Report] - Problems when using with Better Hurt Timer

### ISSUE THREAD

**Issue by Dr-WeiAL** [OneLemonyBoi/MiniUtilities#98]
**Describe the bug**
The damage of Spikes of wood, iron, and gold is normal
But Diamond and Netherite Spikes can cause a lot of damage when paired with Better Hurt Timer.
What are the damage types of these two Spikes? 

One additional sentence: the player will also be killed very quickly, And this problem has appeared in version 1.2.2, but the damage is 1, which means a lot of 1 damage (sans?) in a short period of time.

**To Reproduce**
1. Install [Better Hurt Timer](https://www.curseforge.com/minecraft/mc-mods/better-hurt-timer/download/3268872)
2. Put diamonds or Netherite Spikes on the ground or on the wall
3. Use slabs to make creatures unable to be knocked back, or use other mods' fans and other things to make creatures be Stuck by spikes
4. You can see it, or see the screenshot below

**Expected behavior**
Uh, although the damage is high and it makes people look comfortable, it feels too abnormal, so can it be repaired? 

**Screenshots**
![2021-10-24_06 04 50](https://user-images.githubusercontent.com/47446553/138573016-9ec9598a-6a37-43b7-8b9e-736f107f5e3f.png)
![2021-10-24_06 36 06](https://user-images.githubusercontent.com/47446553/138573626-a2e15523-8b87-484d-b9a2-01751a7bb67f.png)
![2021-10-24_06 18 46](https://user-images.githubusercontent.com/47446553/138573309-95f3a57d-9194-464e-acf0-59f20d55fc23.png)
The above screenshot of 1.2.2

**Mod Info (please complete the following information):**
 - Forge: 3.6.2.2
 - MC Version: 1.16.5
 - Mod Version: 1.2.3

**Additional context**
By the way, I used machine translation, if you don’t understand, please forgive me

**Comment by OneLemonyBoi** [comment]
This is Better Hurt Timer's fault for not checking for a FakePlayer, ask them to fix this bug.

Their Github: https://github.com/BunnyCinnamon/BetterHurtTimer
